Vagrant.configure("2") do |config|
  config.vm.box = "utm/ubuntu-24.04"

  config.vm.provider "utm" do |u|
    u.cpus = 2
    u.memory = 1512
  end

  config.vm.synced_folder "../html", "/var/www/html"
  config.vm.network "forwarded_port", guest: 82, host: 82, auto_correct: true

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y nginx

    sed -i 's/listen 80 default_server;/listen 82 default_server;/g' /etc/nginx/sites-available/default
    sed -i 's/listen \\[::\\]:80 default_server;/listen \\[::\\]:82 default_server;/g' /etc/nginx/sites-available/default

    systemctl restart nginx
  SHELL
end
