if File.exist?(".env")
  File.readlines(".env").each do |line|
    line.strip!
    next if line.empty? || line.start_with?("#")
    key, value = line.split("=", 2)
    ENV[key] = value
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "utm/ubuntu-24.04"

  config.vm.provider "utm" do |u|
    u.cpus = 2
    u.memory = 1512
  end

  # Jenkins server
  config.vm.define "J_SERVER" do |db|
    db.vm.hostname = "j-server-vm"
    db.vm.network "forwarded_port", guest: 4000, host: (ENV["J_SERVER_PROXY_PORT"] || 4000).to_i
    db.vm.network "forwarded_port", guest: 50000, host: 50000
    db.vm.synced_folder "../nodejs_stack", "/opt/nodejs_stack"

    db.vm.provision "shell" do |s|
        s.path = "entrypoint/j-server.sh"
        s.env = {
          "GITHUB_USER" => ENV["GITHUB_USER"],
          "GITHUB_TOKEN" => ENV["GITHUB_TOKEN"],
          "GITHUB_REPO_URL" => ENV["GITHUB_REPO_URL"],
          "DOCKERHUB_USER" => ENV["DOCKERHUB_USER"],
          "DOCKERHUB_PASSWORD" => ENV["DOCKERHUB_PASSWORD"],
          "J_SERVER_PORT" => ENV["J_SERVER_PORT"] || "4000"
        }
    end
  end

  # Jenkins worker
  config.vm.define "J_WORKER" do |app|
    app.vm.hostname = "j-worker-vm"
    app.vm.network "forwarded_port", guest: 4001, host: (ENV["J_WORKER_PROXY_PORT"] || 4001).to_i
    app.vm.synced_folder "../nodejs_stack", "/opt/nodejs_stack"

    app.vm.provision "shell" do |s|
      s.path = "entrypoint/j-worker.sh"
      s.env = {
        "GIT_REPO_URL" => ENV["GIT_REPO_URL"]
      }
    end
  end

  config.trigger.after :up do |trigger|
    trigger.info = "Access Jenkins from your host machine at: http://localhost:#{ENV['J_SERVER_PROXY_PORT'] || 4000}"
  end
end
